version: '3.1'
services:
  minio:
    image: minio/minio:latest
    volumes:
      - data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address :9001 /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
volumes:
  data:
